version: "3"
services:
  php:
    build: ./php
    container_name: php
    # restart: always
    volumes:
      - ./html:/var/www/html
      - ./logs/php:/var/log/php
    ports:
      - 80:80
    depends_on:
      - mysql
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    # restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}

volumes:
  db-store:
